---
dist: xenial
script:
  - make test
jobs:
  fast_finish: true
  include:
    - name: "super-linter"
      language: shell
      script: make super-linter || exit 1;
      stage: linting
    - name: "Setup Debian"
      language: shell
      stage: setup
      script: |
        docker run -it \
          -v $(pwd):/usr/src:ro \
          -w="/usr/src" \
          ubuntu:18.04 \
          /bin/bash -c " \
          export DEBIAN_FRONTEND=noninteractive \
          && echo 'debconf debconf/frontend select Noninteractive' \
          | debconf-set-selections \
          && apt-get -q update \
          && apt-get -qy install git sudo \
          && /usr/src/bin/setup-dotfiles.sh debian \
          && make"
    - name: "Setup macOS"
      os: osx
      osx_image: xcode12.2
      services:
      script: |
        bin/setup-dotfiles.sh macos \
        && make
os: linux
services:
  - docker
stages:
  - linting
  - setup
