---
dist: xenial
script:
  - make test
jobs:
  fast_finish: true
  include:
    - name: "super-linter"
      language: shell
      script: |
        docker run -t \
          -v "$(pwd)":/workspace \
          -w="/workspace" \
          -e ACTIONS_RUNNER_DEBUG=true \
          -e DEFAULT_WORKSPACE=/workspace \
          -e DISABLE_ERRORS=false \
          -e LINTER_RULES_PATH=/workspace \
          -e MULTI_STATUS=false \
          -e RUN_LOCAL=true \
          -e VALIDATE_ALL_CODEBASE=true \
          github/super-linter:V3.8.0
      stage: linting
    - name: "shfmt"
      language: go
      before_install: GO111MODULE=on go get mvdan.cc/sh/v3/cmd/shfmt
      go: "1.14.1"
      script: make shfmt || exit 1;
    - name: "Setup Debian"
      language: shell
      stage: setup
      script: |
        docker run -it \
          -v $(pwd):/usr/src:ro \
          -w="/usr/src" \
          ubuntu:18.04 \
          /bin/bash -c " \
          export DEBIAN_FRONTEND=noninteractive \
          && echo 'debconf debconf/frontend select Noninteractive' \
          | debconf-set-selections \
          && apt-get -q update \
          && apt-get -qy install git sudo \
          && /usr/src/bin/setup-dotfiles.sh debian \
          && make"
    - name: "Setup macOS"
      os: osx
      osx_image: xcode12u
      services:
      script: |
        travis_wait bin/setup-dotfiles.sh macos \
        && make
os: linux
services:
  - docker
stages:
  - linting
  - setup
